<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <!-- Adapters depends on Application ports -->
        <ProjectReference Include="../ConfigSync.Application/ConfigSync.Application.csproj" />
        <!-- credential encryption for the REST mapper -->
        <ProjectReference Include="../ConfigSync.Infrastructure/ConfigSync.Infrastructure.csproj" />
    </ItemGroup>
    <ItemGroup>
        <!-- access to ASP.NET Core types without making project runnable -->
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Npgsql">
            <PrivateAssets>compile;build;buildMultitargeting;buildTransitive;native;contentFiles;analyzers</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Dapper">
            <PrivateAssets>compile;build;buildMultitargeting;buildTransitive;native;contentFiles;analyzers</PrivateAssets>
        </PackageReference>
    </ItemGroup>
    <ItemGroup>
        <!-- to access internal class for testing -->
        <InternalsVisibleTo Include="ConfigSync.Adapters.Tests" />
    </ItemGroup>
</Project>
