services:
  postgres:
    image: postgres:18.4
    container_name: configsync-postgres
    environment:
      POSTGRES_USER: configsync
      POSTGRES_PASSWORD: configsync
      POSTGRES_DB: configsync
    ports:
      - "5432:5432"
    volumes:
      - configsync-postgres-data:/var/lib/postgresql

  atlas-dev-db:
    image: postgres:18.4
    container_name: configsync-atlas-dev-db
    environment:
      POSTGRES_USER: atlas
      POSTGRES_PASSWORD: atlas
      POSTGRES_DB: atlas
    ports:
      - "5433:5432"
  device1:
    image: quay.io/panubo/sshd:1.10.0
    container_name: mock-device1
    environment:
      SSH_USERS: "device:900:900"
    ports:
      - "2201:22"
    volumes:
      - ./mock-devices/keys/mock_devices_key.pub:/etc/authorized_keys/device
      - ./mock-devices/device1/respond.sh:/etc/mock/respond.sh:ro
      - ./mock-devices/device1/force-command.conf:/etc/ssh/sshd_config.d/force-command.conf:ro


volumes:
  configsync-postgres-data: