services:
  postgres:
    image: postgres:18.4
    container_name: configsync-postgres
    environment:
      POSTGRES_USER: configsync
      POSTGRES_PASSWORD: configsync
      POSTGRES_DB: configsync
    ports:
      - "5432:5432"
    volumes:
      - configsync-postgres-data:/var/lib/postgresql

  atlas-dev-db:
    image: postgres:18.4
    container_name: configsync-atlas-dev-db
    environment:
      POSTGRES_USER: atlas
      POSTGRES_PASSWORD: atlas
      POSTGRES_DB: atlas
    ports:
      - "5433:5432"

volumes:
  configsync-postgres-data: