<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <!-- composition root: Main and the DI composition root etc -->
    <ProjectReference Include="../ConfigSync.Domain/ConfigSync.Domain.csproj" />
    <ProjectReference Include="../ConfigSync.Application/ConfigSync.Application.csproj" />
    <ProjectReference Include="../ConfigSync.Adapters/ConfigSync.Adapters.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" />
  </ItemGroup>
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
</Project>