<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <!-- Application depends on Domain -->
    <ProjectReference Include="../ConfigSync.Domain/ConfigSync.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <!-- Rx.NET for reactive-style programming -->
    <PackageReference Include="System.Reactive" />
  </ItemGroup>
</Project>